version: "3.7"
services:
  front:
    image: jatinbhalla18/front
  back:
    image: jatinbhalla18/back
  lb:
    build: ./container-chat-lb-example
    depends_on:
      - front
      - back
    ports:
      - "80:80"
