name: Frontend Chat CI/CD

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
jobs:
   ci:
     runs-on: ubuntu-latest
     container:
       image: node

     steps:
       - uses: actions/checkout@v1
       - name: Install & Tests
         run: |
           npm install
           npm test
#      - name: SonarCloud Scan
#          uses: SonarSource/sonarcloud-github-action@v1.7
#          with:
#            args:
#            projectBaseDir:
#      - name: SonarQube Quality Gate Check
#        uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
#        with:
#        scanMetadataReportFile: # optional, default is .scannerwork/report-task.txt
#      - name: Sonar Build Breaker
#        uses: jkumar19/sonar-build-breaker@3.0.0
#        with:
#        # pass sonar project key
#        project_key: 
#        # pass sonar token
#        sonar_token: 
#        # pass sonar root url
#        sonar_url: 
#        # pass sonar branch name
#        sonar_branch: 
    
   cd:
     runs-on: ubuntu-latest
     needs: ci

     steps:
       - uses: actions/checkout@v1
       - name: Docker login
         run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
       - name: Build
         run: docker build -t front .
       - name: Tags
         run: |
           docker tag front ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
           docker tag front ${{ secrets.DOCKER_USER }}/front:latest
       - name: Push
         run: |
           docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
           docker push ${{ secrets.DOCKER_USER }}/front:latest
